import Head from 'next/head';
//import Image from 'next/image'
import styles from '../styles/Home.module.css';
import material, { FormControlLabel } from '@mui/material';
import Slide from '@mui/material/Slide';
import { useState, useEffect, useMemo } from 'react';

export default function Home() {
  const [descript, setDescript] = useState(0);
  const [index, setIndex] = useState(0);

  const textArray = useMemo(
    () => ['digital', 'development', 'graphics', 'blog'],
    []
  );

  const description = useMemo(
    () => [
      <Slide key="1" direction="right" in={true} mountOnEnter unmountOnExit>
        <p>discover tyty digital and what it can do for you...</p>
      </Slide>,
      <Slide key="2" direction="right" in={true} mountOnEnter unmountOnExit>
        <p>explore what tyty web developent can achieve...</p>
      </Slide>,
      <Slide key="3" direction="right" in={true} mountOnEnter unmountOnExit>
        <p>take centre-stage with beautiful intuative designs...</p>
      </Slide>,
      <Slide key="4" direction="right" in={true} mountOnEnter unmountOnExit>
        <p>weekly updates into the world of tyty digital...</p>
      </Slide>,
    ],
    []
  );

  const desc = useMemo(() => {
    return description[descript];
  }, [descript, description]);

  useEffect(() => {
    // setInterval, not the setTimeout
    const intervalId = setInterval(() => {
      // Index will go up but % will cut it down
      setDescript((prev) => (prev + 1) % description.length);
    }, 3000);

    return () => clearInterval(intervalId);
  }, [description]);

  const text = useMemo(() => {
    return textArray[index];
  }, [index, textArray]);

  useEffect(() => {
    // setInterval, not the setTimeout
    const inter = setInterval(() => {
      // Index will go up but % will cut it down
      setIndex((prev) => (prev + 1) % textArray.length);
    }, 3000);

    return () => clearInterval(inter);
  }, [textArray]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          This is{' '}
          <a style={{ color: '#16a085' }} href="https://nextjs.org">
            tyty <span>{text}</span>
          </a>
        </h1>

        <p className={styles.description}>{desc}</p>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
